apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: loginsignup
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded
  POSTGRES_DB: bG9naW5zaWduX2RkYg==  # base64 encoded
